/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DesignRouteImport } from './routes/design'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VenuesIndexRouteImport } from './routes/venues/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VenuesAddRouteImport } from './routes/venues/add'
import { Route as MembersAddRouteImport } from './routes/members/add'
import { Route as GroupsAddRouteImport } from './routes/groups/add'
import { Route as EventsAddRouteImport } from './routes/events/add'
import { Route as AdminVenuesRouteImport } from './routes/admin/venues'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminGroupsRouteImport } from './routes/admin/groups'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as VenuesVenueIdIndexRouteImport } from './routes/venues/$venueId/index'
import { Route as SettingsTagsIndexRouteImport } from './routes/settings/tags/index'
import { Route as SettingsMemberTypesIndexRouteImport } from './routes/settings/member-types/index'
import { Route as MembersMemberIdIndexRouteImport } from './routes/members/$memberId/index'
import { Route as GroupsGroupIdIndexRouteImport } from './routes/groups/$groupId/index'
import { Route as EventsEventIdIndexRouteImport } from './routes/events/$eventId/index'
import { Route as VenuesVenueIdEditRouteImport } from './routes/venues/$venueId/edit'
import { Route as SettingsTagsAddRouteImport } from './routes/settings/tags/add'
import { Route as SettingsMemberTypesAddRouteImport } from './routes/settings/member-types/add'
import { Route as MembersMemberIdEditRouteImport } from './routes/members/$memberId/edit'
import { Route as GroupsGroupIdEditRouteImport } from './routes/groups/$groupId/edit'
import { Route as EventsEventIdEditRouteImport } from './routes/events/$eventId/edit'
import { Route as SettingsTagsTagIdEditRouteImport } from './routes/settings/tags/$tagId/edit'
import { Route as SettingsMemberTypesMemberTypeIdEditRouteImport } from './routes/settings/member-types/$memberTypeId/edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesIndexRoute = VenuesIndexRouteImport.update({
  id: '/venues/',
  path: '/venues/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VenuesAddRoute = VenuesAddRouteImport.update({
  id: '/venues/add',
  path: '/venues/add',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersAddRoute = MembersAddRouteImport.update({
  id: '/members/add',
  path: '/members/add',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsAddRoute = GroupsAddRouteImport.update({
  id: '/groups/add',
  path: '/groups/add',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsAddRoute = EventsAddRouteImport.update({
  id: '/events/add',
  path: '/events/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVenuesRoute = AdminVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const VenuesVenueIdIndexRoute = VenuesVenueIdIndexRouteImport.update({
  id: '/venues/$venueId/',
  path: '/venues/$venueId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTagsIndexRoute = SettingsTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMemberTypesIndexRoute =
  SettingsMemberTypesIndexRouteImport.update({
    id: '/member-types/',
    path: '/member-types/',
    getParentRoute: () => SettingsRoute,
  } as any)
const MembersMemberIdIndexRoute = MembersMemberIdIndexRouteImport.update({
  id: '/members/$memberId/',
  path: '/members/$memberId/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdIndexRoute = GroupsGroupIdIndexRouteImport.update({
  id: '/groups/$groupId/',
  path: '/groups/$groupId/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesVenueIdEditRoute = VenuesVenueIdEditRouteImport.update({
  id: '/venues/$venueId/edit',
  path: '/venues/$venueId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTagsAddRoute = SettingsTagsAddRouteImport.update({
  id: '/tags/add',
  path: '/tags/add',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMemberTypesAddRoute = SettingsMemberTypesAddRouteImport.update({
  id: '/member-types/add',
  path: '/member-types/add',
  getParentRoute: () => SettingsRoute,
} as any)
const MembersMemberIdEditRoute = MembersMemberIdEditRouteImport.update({
  id: '/members/$memberId/edit',
  path: '/members/$memberId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdEditRoute = GroupsGroupIdEditRouteImport.update({
  id: '/groups/$groupId/edit',
  path: '/groups/$groupId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdEditRoute = EventsEventIdEditRouteImport.update({
  id: '/events/$eventId/edit',
  path: '/events/$eventId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTagsTagIdEditRoute = SettingsTagsTagIdEditRouteImport.update({
  id: '/tags/$tagId/edit',
  path: '/tags/$tagId/edit',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMemberTypesMemberTypeIdEditRoute =
  SettingsMemberTypesMemberTypeIdEditRouteImport.update({
    id: '/member-types/$memberTypeId/edit',
    path: '/member-types/$memberTypeId/edit',
    getParentRoute: () => SettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/design': typeof DesignRoute
  '/settings': typeof SettingsRouteWithChildren
  '/admin/events': typeof AdminEventsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/venues': typeof AdminVenuesRoute
  '/events/add': typeof EventsAddRoute
  '/groups/add': typeof GroupsAddRoute
  '/members/add': typeof MembersAddRoute
  '/venues/add': typeof VenuesAddRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/members/': typeof MembersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/venues/': typeof VenuesIndexRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
  '/groups/$groupId/edit': typeof GroupsGroupIdEditRoute
  '/members/$memberId/edit': typeof MembersMemberIdEditRoute
  '/settings/member-types/add': typeof SettingsMemberTypesAddRoute
  '/settings/tags/add': typeof SettingsTagsAddRoute
  '/venues/$venueId/edit': typeof VenuesVenueIdEditRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
  '/members/$memberId/': typeof MembersMemberIdIndexRoute
  '/settings/member-types/': typeof SettingsMemberTypesIndexRoute
  '/settings/tags/': typeof SettingsTagsIndexRoute
  '/venues/$venueId/': typeof VenuesVenueIdIndexRoute
  '/settings/member-types/$memberTypeId/edit': typeof SettingsMemberTypesMemberTypeIdEditRoute
  '/settings/tags/$tagId/edit': typeof SettingsTagsTagIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/venues': typeof AdminVenuesRoute
  '/events/add': typeof EventsAddRoute
  '/groups/add': typeof GroupsAddRoute
  '/members/add': typeof MembersAddRoute
  '/venues/add': typeof VenuesAddRoute
  '/admin': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/members': typeof MembersIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/venues': typeof VenuesIndexRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
  '/groups/$groupId/edit': typeof GroupsGroupIdEditRoute
  '/members/$memberId/edit': typeof MembersMemberIdEditRoute
  '/settings/member-types/add': typeof SettingsMemberTypesAddRoute
  '/settings/tags/add': typeof SettingsTagsAddRoute
  '/venues/$venueId/edit': typeof VenuesVenueIdEditRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
  '/groups/$groupId': typeof GroupsGroupIdIndexRoute
  '/members/$memberId': typeof MembersMemberIdIndexRoute
  '/settings/member-types': typeof SettingsMemberTypesIndexRoute
  '/settings/tags': typeof SettingsTagsIndexRoute
  '/venues/$venueId': typeof VenuesVenueIdIndexRoute
  '/settings/member-types/$memberTypeId/edit': typeof SettingsMemberTypesMemberTypeIdEditRoute
  '/settings/tags/$tagId/edit': typeof SettingsTagsTagIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/design': typeof DesignRoute
  '/settings': typeof SettingsRouteWithChildren
  '/admin/events': typeof AdminEventsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/venues': typeof AdminVenuesRoute
  '/events/add': typeof EventsAddRoute
  '/groups/add': typeof GroupsAddRoute
  '/members/add': typeof MembersAddRoute
  '/venues/add': typeof VenuesAddRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/members/': typeof MembersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/venues/': typeof VenuesIndexRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
  '/groups/$groupId/edit': typeof GroupsGroupIdEditRoute
  '/members/$memberId/edit': typeof MembersMemberIdEditRoute
  '/settings/member-types/add': typeof SettingsMemberTypesAddRoute
  '/settings/tags/add': typeof SettingsTagsAddRoute
  '/venues/$venueId/edit': typeof VenuesVenueIdEditRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
  '/members/$memberId/': typeof MembersMemberIdIndexRoute
  '/settings/member-types/': typeof SettingsMemberTypesIndexRoute
  '/settings/tags/': typeof SettingsTagsIndexRoute
  '/venues/$venueId/': typeof VenuesVenueIdIndexRoute
  '/settings/member-types/$memberTypeId/edit': typeof SettingsMemberTypesMemberTypeIdEditRoute
  '/settings/tags/$tagId/edit': typeof SettingsTagsTagIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/design'
    | '/settings'
    | '/admin/events'
    | '/admin/groups'
    | '/admin/members'
    | '/admin/venues'
    | '/events/add'
    | '/groups/add'
    | '/members/add'
    | '/venues/add'
    | '/admin/'
    | '/events/'
    | '/groups/'
    | '/members/'
    | '/settings/'
    | '/venues/'
    | '/events/$eventId/edit'
    | '/groups/$groupId/edit'
    | '/members/$memberId/edit'
    | '/settings/member-types/add'
    | '/settings/tags/add'
    | '/venues/$venueId/edit'
    | '/events/$eventId/'
    | '/groups/$groupId/'
    | '/members/$memberId/'
    | '/settings/member-types/'
    | '/settings/tags/'
    | '/venues/$venueId/'
    | '/settings/member-types/$memberTypeId/edit'
    | '/settings/tags/$tagId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/admin/events'
    | '/admin/groups'
    | '/admin/members'
    | '/admin/venues'
    | '/events/add'
    | '/groups/add'
    | '/members/add'
    | '/venues/add'
    | '/admin'
    | '/events'
    | '/groups'
    | '/members'
    | '/settings'
    | '/venues'
    | '/events/$eventId/edit'
    | '/groups/$groupId/edit'
    | '/members/$memberId/edit'
    | '/settings/member-types/add'
    | '/settings/tags/add'
    | '/venues/$venueId/edit'
    | '/events/$eventId'
    | '/groups/$groupId'
    | '/members/$memberId'
    | '/settings/member-types'
    | '/settings/tags'
    | '/venues/$venueId'
    | '/settings/member-types/$memberTypeId/edit'
    | '/settings/tags/$tagId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/design'
    | '/settings'
    | '/admin/events'
    | '/admin/groups'
    | '/admin/members'
    | '/admin/venues'
    | '/events/add'
    | '/groups/add'
    | '/members/add'
    | '/venues/add'
    | '/admin/'
    | '/events/'
    | '/groups/'
    | '/members/'
    | '/settings/'
    | '/venues/'
    | '/events/$eventId/edit'
    | '/groups/$groupId/edit'
    | '/members/$memberId/edit'
    | '/settings/member-types/add'
    | '/settings/tags/add'
    | '/venues/$venueId/edit'
    | '/events/$eventId/'
    | '/groups/$groupId/'
    | '/members/$memberId/'
    | '/settings/member-types/'
    | '/settings/tags/'
    | '/venues/$venueId/'
    | '/settings/member-types/$memberTypeId/edit'
    | '/settings/tags/$tagId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DesignRoute: typeof DesignRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  EventsAddRoute: typeof EventsAddRoute
  GroupsAddRoute: typeof GroupsAddRoute
  MembersAddRoute: typeof MembersAddRoute
  VenuesAddRoute: typeof VenuesAddRoute
  EventsIndexRoute: typeof EventsIndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  MembersIndexRoute: typeof MembersIndexRoute
  VenuesIndexRoute: typeof VenuesIndexRoute
  EventsEventIdEditRoute: typeof EventsEventIdEditRoute
  GroupsGroupIdEditRoute: typeof GroupsGroupIdEditRoute
  MembersMemberIdEditRoute: typeof MembersMemberIdEditRoute
  VenuesVenueIdEditRoute: typeof VenuesVenueIdEditRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
  GroupsGroupIdIndexRoute: typeof GroupsGroupIdIndexRoute
  MembersMemberIdIndexRoute: typeof MembersMemberIdIndexRoute
  VenuesVenueIdIndexRoute: typeof VenuesVenueIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/': {
      id: '/venues/'
      path: '/venues'
      fullPath: '/venues/'
      preLoaderRoute: typeof VenuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/venues/add': {
      id: '/venues/add'
      path: '/venues/add'
      fullPath: '/venues/add'
      preLoaderRoute: typeof VenuesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/add': {
      id: '/members/add'
      path: '/members/add'
      fullPath: '/members/add'
      preLoaderRoute: typeof MembersAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/add': {
      id: '/groups/add'
      path: '/groups/add'
      fullPath: '/groups/add'
      preLoaderRoute: typeof GroupsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/add': {
      id: '/events/add'
      path: '/events/add'
      fullPath: '/events/add'
      preLoaderRoute: typeof EventsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/venues': {
      id: '/admin/venues'
      path: '/venues'
      fullPath: '/admin/venues'
      preLoaderRoute: typeof AdminVenuesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/venues/$venueId/': {
      id: '/venues/$venueId/'
      path: '/venues/$venueId'
      fullPath: '/venues/$venueId/'
      preLoaderRoute: typeof VenuesVenueIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/tags/': {
      id: '/settings/tags/'
      path: '/tags'
      fullPath: '/settings/tags/'
      preLoaderRoute: typeof SettingsTagsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/member-types/': {
      id: '/settings/member-types/'
      path: '/member-types'
      fullPath: '/settings/member-types/'
      preLoaderRoute: typeof SettingsMemberTypesIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/members/$memberId/': {
      id: '/members/$memberId/'
      path: '/members/$memberId'
      fullPath: '/members/$memberId/'
      preLoaderRoute: typeof MembersMemberIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/': {
      id: '/groups/$groupId/'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId/'
      preLoaderRoute: typeof GroupsGroupIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$venueId/edit': {
      id: '/venues/$venueId/edit'
      path: '/venues/$venueId/edit'
      fullPath: '/venues/$venueId/edit'
      preLoaderRoute: typeof VenuesVenueIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/tags/add': {
      id: '/settings/tags/add'
      path: '/tags/add'
      fullPath: '/settings/tags/add'
      preLoaderRoute: typeof SettingsTagsAddRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/member-types/add': {
      id: '/settings/member-types/add'
      path: '/member-types/add'
      fullPath: '/settings/member-types/add'
      preLoaderRoute: typeof SettingsMemberTypesAddRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/members/$memberId/edit': {
      id: '/members/$memberId/edit'
      path: '/members/$memberId/edit'
      fullPath: '/members/$memberId/edit'
      preLoaderRoute: typeof MembersMemberIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/edit': {
      id: '/groups/$groupId/edit'
      path: '/groups/$groupId/edit'
      fullPath: '/groups/$groupId/edit'
      preLoaderRoute: typeof GroupsGroupIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/edit': {
      id: '/events/$eventId/edit'
      path: '/events/$eventId/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof EventsEventIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/tags/$tagId/edit': {
      id: '/settings/tags/$tagId/edit'
      path: '/tags/$tagId/edit'
      fullPath: '/settings/tags/$tagId/edit'
      preLoaderRoute: typeof SettingsTagsTagIdEditRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/member-types/$memberTypeId/edit': {
      id: '/settings/member-types/$memberTypeId/edit'
      path: '/member-types/$memberTypeId/edit'
      fullPath: '/settings/member-types/$memberTypeId/edit'
      preLoaderRoute: typeof SettingsMemberTypesMemberTypeIdEditRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEventsRoute: typeof AdminEventsRoute
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminVenuesRoute: typeof AdminVenuesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEventsRoute: AdminEventsRoute,
  AdminGroupsRoute: AdminGroupsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminVenuesRoute: AdminVenuesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SettingsRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsMemberTypesAddRoute: typeof SettingsMemberTypesAddRoute
  SettingsTagsAddRoute: typeof SettingsTagsAddRoute
  SettingsMemberTypesIndexRoute: typeof SettingsMemberTypesIndexRoute
  SettingsTagsIndexRoute: typeof SettingsTagsIndexRoute
  SettingsMemberTypesMemberTypeIdEditRoute: typeof SettingsMemberTypesMemberTypeIdEditRoute
  SettingsTagsTagIdEditRoute: typeof SettingsTagsTagIdEditRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsMemberTypesAddRoute: SettingsMemberTypesAddRoute,
  SettingsTagsAddRoute: SettingsTagsAddRoute,
  SettingsMemberTypesIndexRoute: SettingsMemberTypesIndexRoute,
  SettingsTagsIndexRoute: SettingsTagsIndexRoute,
  SettingsMemberTypesMemberTypeIdEditRoute:
    SettingsMemberTypesMemberTypeIdEditRoute,
  SettingsTagsTagIdEditRoute: SettingsTagsTagIdEditRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DesignRoute: DesignRoute,
  SettingsRoute: SettingsRouteWithChildren,
  EventsAddRoute: EventsAddRoute,
  GroupsAddRoute: GroupsAddRoute,
  MembersAddRoute: MembersAddRoute,
  VenuesAddRoute: VenuesAddRoute,
  EventsIndexRoute: EventsIndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  MembersIndexRoute: MembersIndexRoute,
  VenuesIndexRoute: VenuesIndexRoute,
  EventsEventIdEditRoute: EventsEventIdEditRoute,
  GroupsGroupIdEditRoute: GroupsGroupIdEditRoute,
  MembersMemberIdEditRoute: MembersMemberIdEditRoute,
  VenuesVenueIdEditRoute: VenuesVenueIdEditRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
  GroupsGroupIdIndexRoute: GroupsGroupIdIndexRoute,
  MembersMemberIdIndexRoute: MembersMemberIdIndexRoute,
  VenuesVenueIdIndexRoute: VenuesVenueIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
