export type TextFieldType = "text" | "password" | "email" | "tel" | "url";

export type AutoCompleteTokens =
  | "off"
  | "on"
  | "tel"
  | "tel-country-code"
  | "tel-national"
  | "tel-area-code"
  | "tel-local"
  | "home tel"
  | "home tel-country-code"
  | "home tel-national"
  | "work tel"
  | "work tel-country-code"
  | "work tel-national"
  | "work tel-area-code"
  | "work tel-local"
  | "mobile tel"
  | "mobile tel-country-code"
  | "mobile tel-national"
  | "mobile tel-area-code"
  | "mobile tel-local"
  | "fax tel"
  | "fax tel-country-code"
  | "fax tel-national"
  | "fax tel-area-code"
  | "fax tel-local"
  | "pager tel"
  | "pager tel-country-code"
  | "pager tel-national"
  | "pager tel-area-code"
  | "pager tel-local"
  | "email"
  | "home email"
  | "work email"
  | "impp"
  | "name"
  | "honorific-prefix"
  | "given-name"
  | "additional-name"
  | "family-name"
  | "honorific-suffix"
  | "nickname"
  | "username"
  | "new-password"
  | "current-password"
  | "one-time-code"
  | "organization-title"
  | "organization"
  | "street-address"
  | "address-line1"
  | "address-line2"
  | "address-line3"
  | "address-level1"
  | "address-level2"
  | "address-level3"
  | "address-level4"
  | "country"
  | "country-name"
  | "country-code"
  | "postal-code"
  | "home street-address"
  | "home address-line1"
  | "home address-line2"
  | "home address-line3"
  | "home address-level1"
  | "home address-level2"
  | "home address-level3"
  | "home address-level4"
  | "home country"
  | "home country-name"
  | "home country-code"
  | "home postal-code"
  | "work street-address"
  | "work address-line1"
  | "work address-line2"
  | "work address-line3"
  | "work address-level1"
  | "work address-level2"
  | "work address-level3"
  | "work address-level4"
  | "work country"
  | "work country-name"
  | "work country-code"
  | "work postal-code"
  | "cc-name"
  | "cc-given-name"
  | "cc-additional-name"
  | "cc-family-name"
  | "cc-number"
  | "cc-exp"
  | "cc-exp-month"
  | "cc-exp-year"
  | "cc-csc"
  | "cc-type"
  | "transaction-currency"
  | "transaction-amount"
  | "language"
  | "bday"
  | "bday-day"
  | "bday-month"
  | "bday-year"
  | "sex"
  | "url"
  | "home url"
  | "work url"
  | "photo"
  | "webauthn";
